export const LOGIN_SET = 'LOGIN_SET';
export const LOGIN_MODAL_TOGGLE = 'LOGIN_MODAL_TOGGLE';
export const SUBURB_SELECT = 'SUBURB_SELECT';
export const SUBURB_POPULATE = 'SUBURB_POPULATE';
export const SUBURB_SHOW_CONTENT = 'SUBURB_SHOW_CONTENT';
export const USER_SELECT = 'USER_SELECT';